[package]
name = "find_focus"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3.0.0"
poem-openapi = { features = ["swagger-ui", "email"] }
slab = "0.4.9"
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }
